version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # Variáveis para a conexão com o banco de dados
      - DATABASE_URL=postgres://zuln_user:${POSTGRES_PASSWORD}@db:5432/zuln_db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # Variáveis para a configuração do PostgreSQL
      - POSTGRES_DB=zuln_db
      - POSTGRES_USER=zuln_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data: