# Generated by Django 5.2.5 on 2025-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome ou Modelo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('imagem', models.ImageField(upload_to='espelhos/', verbose_name='Imagem')),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largura(cm)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura(cm)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Espelho',
                'verbose_name_plural': 'Espelhos',
                'ordering': ['nome'],
            },
        ),
    ]
