# Generated by Django 5.2.5 on 2025-08-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espelho',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='espelho',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='espelho',
            name='largura',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largura (cm)'),
        ),
        migrations.CreateModel(
            name='FotoEspelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='espelhos/galeria/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('espelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='loja.espelho', verbose_name='Espelho')),
            ],
            options={
                'verbose_name': 'Foto do Espelho',
                'verbose_name_plural': 'Fotos dos Espelhos',
                'ordering': ['ordem'],
            },
        ),
    ]
